name: release

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    tags:
      - "[0-9]+.*"

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

jobs:
  release:
    runs-on: ${{ matrix.os }}
    name: release (${{ matrix.os }})

    strategy:
      matrix:
        include:
          - os: windows-latest
          # - os: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.os == 'macos-latest' && 'x86_64-apple-darwin' || '' }}

      - uses: taiki-e/install-action@v2
        with:
          tool: just

      # - name: macos bundles
      #   if: matrix.os == 'macos-latest'
      #   run: |
      #     pnpm i
      #     just build-tauri
      #     node --run bundle:tauri:mac
      #     just build-electron
      #     node --run bundle:electron

      # - uses: softprops/action-gh-release@v2
      #   with:
      #     name: try-release
      #     tag_name: try-release
      #     draft: true

      - name: windows bundles
        if: matrix.os == 'windows-latest'
        run: |
          pnpm i
          just build-tauri
          node --run bundle:tauri:win
          just build-electron
          node --run bundle:electron

      - uses: softprops/action-gh-release@v2
        if: matrix.os == 'windows-latest'
        with:
          name: try-release
          draft: true
          files: |
            ./target/release/bundle/nsis/*.exe
            ./electron-bundle/*.exe
